[package]
name = "tw_bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.0"
tw_keypair = { path = "../tw_keypair" }
tw_hash = { path = "../tw_hash" }
ripemd = "0.1.3"
secp256k1 = { version = "0.27.0", features = [ "global-context", "rand" ] }
rand = { version = "0.8.5", features = [ "std_rng" ] }
