[package]
name = "codegen_fabio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "system"
path = "src/lib.rs"

[[bin]]
name = "parser"
path = "src/bin/main.rs"

[dependencies]
